# Generated by Django 4.2.4 on 2023-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_node_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
