# Generated by Django 4.2.4 on 2023-08-20 09:02

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_node_x_node_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
